### PR TITLE
Removed the runtime-fmt crate to fix compilation

### PR DESCRIPTION
**Pull request by vkomenda**
Compilation error that is fixed by the PR: https://travis-ci.org/Fantom-foundation/full-cli-rs/jobs/566542057

### CODE REVIEW

**Comment by AgustinCB** [comment]
What do you mean "to fix compilation"? It compiles on my machine. What's your toolbox?

**Comment by AgustinCB** [comment]
And that change actually _breaks_ the println function

**Comment by vkomenda** [comment]
I updated the description above with the compilation error.

I agree that the output of `println` may not be the same. Can we make the output match what it was with `rt_println`? In any case, at least the library compiles now.

**Comment by AgustinCB** [comment]
No, not really, `rt_println` is meant to work as the `printf` function in C. It's ok to add the degradation for the demo, but we do have to document it and fix it afterwards.

**Comment by vkomenda** [comment]
Can you explain that a bit please? I don't understand why `rt_println` is required. The format strings were all static, like `"{}"`. I think that `println` suffices in this case and the dependency on `runtime-fmt` can be avoided. Can you show a sample output that you expect?

**Comment by AgustinCB** [comment]
`rt_print` receives as the first argument a string with the content to print in C format (i.e. something like "You paid %d"). That string can have a lifetime different that `'static` that is defined by the user at runtime. Think of this example use case of a user using the VM:

User puts in the stack the integer 5. User puts in the stack the string "You paid %d". User calls the internal function `printf` with the arguments that are in the stack. The internal function grabs the first value in the stack and binds it to `content` and puts the rest of the values in the registers.

In this context, `content` doesn't have static lifetime.

`println!` only accepts strings with static lifetimes.

**Comment by vkomenda** [comment]
Thanks! I see now. I think it would be wrong to merge this PR as is. We need a better fix.

**Comment by vkomenda** [comment]
Closing in favour of #4.

**Pull request closed without merging**
